# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # npm/yarn (/**/package.json)
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
      timezone: Japan
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - 'dependabot:robot:'
    open-pull-requests-limit: 10

  # GitHub Actions (/.github/workflows/*.yml)
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
      timezone: Japan
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - 'dependabot:robot:'
