name: Node CI

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - '**'
      - '!**.md' # Exclude Markdown
  pull_request:
    paths:
      - '**'
      - '!**.md' # Exclude Markdown

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      # Setup Environment
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Dependencies
        uses: actions/cache@v2.1.0
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v1
      - name: Drafts next Release notes
        if: github.event_name == 'push' && !contains(github.ref, 'tags/v')
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive Production Artifact
        if: ${{ always() }} && contains(github.ref, 'tags/v') # works only version tagged
        uses: actions/upload-artifact@v2.1.3
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: [build]
    if: github.event_name == 'push' && contains(github.ref, 'tags/v') # works only version tagged
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Download Production Artifact
        uses: actions/download-artifact@v2.0.3
        with:
          name: dist
      - name: Get Version
        id: get_tag
        run: echo ::set-output name=version::${TAG_REF_NAME##*/}
        env:
          TAG_REF_NAME: ${{ github.ref }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: cs.ddradar.app
          commit_message: 'build: release ${{ steps.get_tag.outputs.version }} via '
