name: Node.js CI/CD

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 16

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload Production Artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: dist

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Unit Test
        run: yarn test --coverage

      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v3.1.1

  deploy:
    name: Deploy
    needs: [build, test]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.2
