name: Node.js CI/CD

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

env:
  NODE_VERSION: 12

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Archive Production Artifact
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dist
          path: dist

  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Unit Test
        run: yarn test --coverage

      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v3.1.0

  deploy:
    name: Deploy
    needs: [build]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download Production Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: cs.ddradar.app
          commit_message: 'build: release ${{ github.event.release.tag_name }} via '
